"""Sawn-joist floor framing with explicit support and blocking decisions."""
import math
from .assemblies import WallFrame, _number
from ._assembly import Builder, positions, section


def floor_frame(project, id, *, width, depth, joist_stock, frame=WallFrame(),
                spacing=16, joist_axis=None, direction_reason='', blocking_rows=(),
                maximum_block_spacing=None, blocking_basis='', support_ids=(),
                panel_stock=None, panel_thickness=.75, panel_edges='blocked',
                panel_joint_basis='', assembly='Floor framing'):
    """Outside-rim dimensions; frame origin is the underside of the joists.

    Default joists span the shorter dimension. An override requires its support
    rationale. Blocking rows are distances along the joists, not along the rim.
    maximum_block_spacing is a sourced design input, never an inferred code limit.
    Only solid rectangular sawn joists are generated by this builder.
    """
    for value,name in ((width,'width'),(depth,'depth')): _number(value,name)
    t,h=section(project,joist_stock)
    chosen=0 if width<=depth else 1
    if joist_axis is not None:
        if type(joist_axis)!=int or joist_axis not in (0,1): raise ValueError('joist_axis must be 0 or 1')
        if joist_axis!=chosen and not str(direction_reason).strip():
            raise ValueError('Alternative joist direction needs a support-layout reason')
        chosen=joist_axis
    # Local U follows joist length; V distributes joists. For axis 1 reflect
    # the transverse direction so the same outside rectangle is retained.
    workframe=frame if chosen==0 else WallFrame(frame.origin,frame.angle+90*frame.inward,-frame.inward)
    span,cross=(width,depth) if chosen==0 else (depth,width)
    ys=positions(cross,spacing,t)
    if span<=2*t: raise ValueError('Floor span must fit rims and joists')
    b=Builder(project,id,workframe,'floor_frame',assembly)
    rows=set()
    for row in blocking_rows:
        _number(row,'blocking row')
        rows.add(row)
    if maximum_block_spacing is not None:
        _number(maximum_block_spacing,'maximum_block_spacing',minimum=t)
        if not str(blocking_basis).strip(): raise ValueError('Blocking interval requires its source/design basis')
        # Equal segments include end restraint; maximum is distance between rows.
        count=math.ceil((span-t)/maximum_block_spacing)
        rows.update(t/2+(span-t)*i/count for i in range(1,count))
    if panel_edges not in ('blocked','tongue_and_groove'):
        raise ValueError('panel_edges must be blocked or tongue_and_groove')
    if panel_edges=='tongue_and_groove' and panel_stock and not str(panel_joint_basis).strip():
        raise ValueError('Tongue-and-groove edges need a product/detail basis')
    u_edges=[0,span];v_edges=[0,cross]
    if panel_stock:
        if panel_stock not in project.stocks or not project.stocks[panel_stock].sheet:
            raise ValueError('Subfloor requires registered sheet stock')
        _number(panel_thickness,'panel_thickness')
        short,long=sorted(project.stocks[panel_stock].sheet)
        u_edges=sorted(set([0,span]+[float(x) for x in _multiples(short,span)]))
        v_edges=sorted(set([0,cross]+[float(x) for x in _multiples(long,cross)]))
        # Sheet ends must bear on actual joists, independent of panel system.
        for edge in v_edges[1:-1]:
            if not any(abs(y+t/2-edge)<.001 for y in ys):
                raise ValueError('Panel end joints must align with joist centers; adjust spacing or sheet layout')
        if panel_edges=='blocked': rows.update(u_edges[1:-1])
    ordered=sorted(rows)
    if any(row-t/2<t or row+t/2>span-t for row in ordered):
        raise ValueError('Blocking must fit between rim inner faces')
    if any(y-x<t for x,y in zip(ordered,ordered[1:])):
        raise ValueError('Blocking rows overlap; consolidate the blocking plan')
    rims=[b.box(f'rim.{i}',joist_stock,(u,0,0),(t,cross,h)) for i,u in enumerate((0,span-t))]
    joists=[]
    for i,y in enumerate(ys):
        pid=b.box(f'joist.{i}',joist_stock,(t,y,0),(span-2*t,t,h))
        joists.append(pid)
        for end,rim in enumerate(rims):
            b.require(f'end.{i}.{end}','Full-depth joist end restraint','minimum_contact',[pid,rim],minimum_area=t*h)
    blocks=[];block_groups=[]
    for row_index,u in enumerate(ordered):
        row_ids=[];block_groups.append(row_ids)
        for bay,(y0,y1) in enumerate(zip(ys,ys[1:])):
            pid=b.box(f'blocking.{row_index}.{bay}',joist_stock,(u-t/2,y0+t,0),(t,y1-y0-t,h))
            blocks.append(pid);row_ids.append(pid)
            for j in (bay,bay+1):
                b.require(f'block.{row_index}.{bay}.{j}', 'Blocking meets adjacent joist',
                          'minimum_contact',[pid,joists[j]],minimum_area=t*h)
    if maximum_block_spacing is not None:
        a=workframe.point(0,0,0);end=workframe.point(1,0,0)
        groups=[[rims[0]],*block_groups,[rims[1]]]
        b.require('blocking_interval','Selected lateral-restraint interval','blocking_spacing',sum(groups,[]),
                  rows=groups,direction=[v-u for v,u in zip(end,a)],maximum_spacing=maximum_block_spacing)
    if not support_ids:
        b.unverified('bearing','Floor beam/foundation bearing and anchorage are not specified; end restraint is not vertical support.')
    else:
        existing={p['id']:p for p in project.parts}
        if any(pid not in existing for pid in support_ids): raise ValueError('Unknown floor support part')
        for i,pid in enumerate(joists):
            for j,support in enumerate(support_ids):
                b.require(f'bearing.{i}.{j}','Declared floor bearing contact','minimum_contact',
                          [pid,support],minimum_area=t*t,normal=[0,0,-1])
    supports=rims+joists+blocks
    panels={}
    for i,(u0,u1) in enumerate(zip(u_edges,u_edges[1:])) if panel_stock else []:
        for j,(v0,v1) in enumerate(zip(v_edges,v_edges[1:])):
            pid=b.box(f'panel.{i}.{j}',panel_stock,(u0,v0,h),(u1-u0,v1-v0,panel_thickness))
            panels[i,j]=pid
            edges=['1:0','1:1']
            if panel_edges=='blocked' or i==0: edges.append('0:0')
            if panel_edges=='blocked' or i==len(u_edges)-2: edges.append('0:1')
            b.require(f'panel_support.{i}.{j}','Subfloor edge bearing','panel_support',[pid,*supports],
                      thickness_axis=2,bearing_width=t/2,edges=edges)
            if panel_edges=='tongue_and_groove' and i:
                b.require(f'panel_joint.{i}.{j}','Specified T&G panel joint','panel_joint',
                          [panels[i-1,j],pid],thickness_axis=2,minimum_area=(v1-v0)*panel_thickness,basis=panel_joint_basis)
    b.unverified('capacity','Sawn joist capacity, deflection, connections and blocking applicability need the selected species/grade, loads and adopted design requirements.')
    if panel_stock:
        b.unverified('panel_installation','Panel strength axis, fastening, installation gaps and cutting layout must follow the selected panel product. Modeled joints are nominal meeting planes.')
    b.result.interfaces.update(width=width,depth=depth,joist_axis=chosen,
        joist_span=span-2*t,joist_depth=h,blocking_rows=ordered,
        blocking_basis=blocking_basis,panel_edges=panel_edges,
        top_elevation=frame.origin[2]+h+(panel_thickness if panel_stock else 0),
        support_ids=list(support_ids),direction_reason=direction_reason)
    return b.commit()


def _multiples(step,limit):
    value=step
    while value<limit-.001:
        yield value
        value+=step
